# [rust]
# edition = "2021"

[book]
authors = ["Quaternijkon"]
language = "zh-CN"
# multilingual = false
src = "src"
title = "paper_reading"

# [preprocessor.reading-time]

[output.html]
# git-repository-url = "https://github.com/Quaternijkon/paper"
# edit-url-template = "https://github.com/Quaternijkon/paper/edit/main/{path}"
# additional-css = ["config/whichlang.css","theme/pagetoc.css"]
# additional-js = ["config/whichlang.js","theme/pagetoc.js"]

[output.html.fold]
enable = true
level = 0

