[book]
authors = ["Quaternijkon"]
language = "zh-CN"
# multilingual = false
src = "src"
title = "paper_reading"

# [preprocessor.reading-time]

[output.html]
git-repository-url = "https://github.com/Quaternijkon/paper"
edit-url-template = "https://github.com/Quaternijkon/paper/edit/main/{path}"

[output.html.fold]
enable = true
level = 0